### ISSUE TITLE
Bot won't work unless there's a "logs" folder in the main folder.

### ISSUE THREAD

**Issue by Kurolox** [SaschaMann/TriviaBot#17]
The bot doesn't generate it, so it will complain until you create that folder by hand.

**Comment by Datkros** [comment]
shouldn't we close this? I fixed that a few days ago

**Comment by SaschaMann** [comment]
@Datkros If you mention something like "Fixes #17" in the PR, it'll automatically close the issue when merged, please do so next time ;)
