### ISSUE TITLE
Implement Question generators

### ISSUE THREAD

**Issue by SaschaMann** [SaschaMann/TriviaBot#6]
Write the logic to generate questions via the static API based on types such as
- [ ] Gold cost of items
- [ ] Champion Names
- [ ] Skill Names

etc.

I will add a better list later on.

**Comment by terry182** [comment]
Hi:) I would like to give it a try but what do you mean about champion Names? questioning champion names providing champion skills ?

**Comment by RonakR** [comment]
Hey @terry182, while this one seems like a juicy one to do, I'd say leave this for @SaschaMann or me as we have a lot of experience with the current trivia bot on the League IRC channel.

**Comment by SaschaMann** [comment]
@terry182 

8598f20 contains two examples for question generators.

The idea is that you pull some data from the static league of legends and then randomly generate a Question object from it.

It can be anything like Champion Name from Title, Champion Name from Lore, Champion Name from Skill names etc. Just be creative with the data you can get from the API.

For now I'd stick to data you can via riotwatcher. We will probably extend it later on as there are a few question-types that we want to implement that can't get from it.
