### ISSUE TITLE
Add helptext to all available commands

### ISSUE THREAD

**Issue by SaschaMann** [SaschaMann/TriviaBot#8]
Add examples and a brief description of what every command does. Relies on #7 being finished.

**Comment by Kurolox** [comment]
Working on this one.

**Comment by shashankaryan** [comment]
hi, i want to take this. in which file i need to update?

**Comment by Kurolox** [comment]
I'm afraid that you can't take it yet since as the description says, it relies in #7. I'm doing #7 right now, but is still not in the program. I apologize.

**Comment by shashankaryan** [comment]
okay. no issues.

**Comment by SaschaMann** [comment]
Currently all the commands have helptexts. This is more of an ongoing issue/TODO when adding new issues so there's no direct work to be done atm
