### ISSUE TITLE
Implement trivia logic

### ISSUE THREAD

**Issue by SaschaMann** [SaschaMann/TriviaBot#9]
This is the most critical part at the moment. The following functionality has to be added:

- [x] Start a new Question
- [x] Listen for answers & check if they are correct
- [x] Show the right solution after time to answer is over & stop listening for answers

**Comment by terry182** [comment]
I am trying to work on this issue :)

**Comment by SaschaMann** [comment]
Most of this is already done, just the timer that stops the question and
reveals the answer if nobody answered correctly within X seconds has to be
added.

**Comment by SaschaMann** [comment]
Resolved.
